### ISSUE TITLE
Support markdown on ImageAttribution

### ISSUE THREAD

**Issue by atiq-cs** [atiq-cs/statiq-template#9]
Utilize markdown instead of html on ImageAttribution

![image](https://user-images.githubusercontent.com/7858031/206035344-da078357-ed9e-445d-a6c7-104166f81914.png)

Screenshot shows the state when markdown is used on attribution.

**Comment by atiq-cs** [comment]
@rdeago please have a look

**Comment by rdeago** [comment]
Silly me, I should have replied here instead of in #8.

> I understand the rationale and totally agree in principle: HTML knowledge is not required to write a post, so why should one have to deal with tags just for image attribution?
> 
> Unfortunately, Markdown just won't work here, unless the theme's Razor code is changed to somehow call the Markdown renderer instead of injecting `ImageAttribution` as raw HTML.
> 
> I'm afraid I'm at a loss here - tagging @daveaglick in the hope he may help.
> 
> As a side note, most stock photography sites have copypaste-ready attribution HTML. See for example:
> 
> * [Unsplash](https://unsplash.com/photos/urnV5XxCuA4) (click on "Download free"; find attribution code
> * in the pop-up, with a nice Copy button)
> * [Pexels](https://www.pexels.com/photo/brown-concrete-building-on-top-of-mountain-14558772) (same as Unsplash)
> * [Freepik](https://www.freepik.com/free-photo/house-isolated-field_10025444.htm) (click on "Download", then on "Free download"; find attribution code, and the Copy button, right in the middle of the image)
> 
> Even when that is not available, as is your case with DALL-E2 for example, the most complicated HTML one would have to write is one or two `<a>` tags. So yes, the principle still stands, but enforcing it here might be less than paramount.

**Comment by atiq-cs** [comment]
Completed by commit statiqdev/CleanBlog@8543531.
